spring.application.name=jobportal

spring.datasource.url=jdbc:mysql://localhost:3306/jobportaldb
spring.datasource.username=jobportal
spring.datasource.password=JobPortal123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080